# Generated by Django 4.0.4 on 2022-09-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comp_level',
            field=models.SmallIntegerField(choices=[(0, 'Temporer'), (1, 'Staff'), (2, 'Supervisor'), (3, 'Manager'), (4, 'Senior Manager'), (5, 'Top Manager')], default=1, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comp_stat',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.company'),
        ),
    ]
