# Generated by Django 4.0.4 on 2022-09-03 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_author'),
        ('accounts', '0002_profile_comp_level_profile_comp_stat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', related_query_name='employee', to='company.company'),
        ),
    ]
