# Generated by Django 4.0.4 on 2022-09-02 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='comp_author', related_query_name='comp_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
