# Generated by Django 4.0.4 on 2022-09-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Config',
        ),
    ]
