# Generated by Django 4.1.2 on 2023-02-05 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_alter_company_options_company_config_delete_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comp_author', related_query_name='comp_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_editors', related_query_name='comp_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
