# Generated by Django 4.0.4 on 2022-08-19 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('legal', models.CharField(choices=[('ud', 'UD'), ('cv', 'CV'), ('pt', 'PT'), ('kp', 'Koperasi'), ('ys', 'Yayasan'), ('ot', 'Lainnya')], default='ot', max_length=3)),
                ('business_type', models.CharField(max_length=125)),
                ('address', models.CharField(max_length=125)),
                ('city', models.CharField(max_length=125)),
                ('country', models.CharField(max_length=125)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/default/company.png', upload_to='images/accounting/company/')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='COH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=125, unique=True, verbose_name='account header')),
                ('group', models.IntegerField(choices=[(1, 'ASSET'), (2, 'LIABILITY'), (3, 'EQUITY'), (4, 'REVENUE'), (5, 'EXPENSE'), (6, 'GAIN'), (7, 'LOSES'), (9, 'OTHER')], verbose_name='account group')),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/default/COH.png', upload_to='images/COH/')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'COH',
                'verbose_name_plural': 'COH',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='COA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=125, unique=True, verbose_name='account name')),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('normal', models.CharField(choices=[('d', 'DEBIT'), ('c', 'CREDIT')], max_length=1, verbose_name='normal balance')),
                ('is_cashflow', models.BooleanField(default=False, verbose_name='is cash flow')),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/default/COA.png', upload_to='images/COA/')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', to='accounting.coh', verbose_name='account header')),
            ],
            options={
                'verbose_name': 'COA',
                'verbose_name_plural': 'COA',
                'ordering': ('number',),
            },
        ),
    ]
