# Generated by Django 4.0.4 on 2022-08-31 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BSG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.FloatField(unique=True)),
                ('name', models.CharField(max_length=125, unique=True, verbose_name='account name')),
                ('group', models.CharField(max_length=125, verbose_name='type')),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/default/bsg.png', upload_to='images/bsg/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bsg_authors', related_query_name='bsg_author', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bsg_editors', related_query_name='bsg_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BSG',
                'verbose_name_plural': 'BSG',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='CCF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.FloatField(unique=True)),
                ('name', models.CharField(max_length=125, unique=True, verbose_name='account name')),
                ('flow', models.CharField(choices=[('i', 'INFLOW'), ('o', 'OUTFLOW')], max_length=1)),
                ('activity', models.IntegerField(choices=[(1, 'OPERATING'), (2, 'INVESTING'), (3, 'FINANCING'), (4, 'OTHERS')])),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/default/ccf.png', upload_to='images/accounting/ccf/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ccf_authors', related_query_name='ccf_author', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ccf_editors', related_query_name='ccf_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CCF',
                'verbose_name_plural': 'CCF',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='COA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.FloatField(unique=True)),
                ('name', models.CharField(max_length=125, unique=True, verbose_name='account name')),
                ('normal', models.CharField(choices=[('d', 'DEBIT'), ('c', 'CREDIT')], max_length=1, verbose_name='normal balance')),
                ('is_cashflow', models.BooleanField(default=False, verbose_name='is cash flow')),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/default/coa.png', upload_to='images/accounting/coa/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coa_authors', related_query_name='coa_author', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coa_editors', related_query_name='coa_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'COA',
                'verbose_name_plural': 'COA',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='JRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=125)),
                ('group', models.CharField(max_length=125, verbose_name='type')),
                ('image', models.ImageField(default='images/default/jrb.png', upload_to='images/jrb/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jrb_authors', related_query_name='jrb_author', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jrb_editors', related_query_name='jrb_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JRB',
                'verbose_name_plural': 'JRB',
            },
        ),
        migrations.CreateModel(
            name='JRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('number', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('d', 'DEBIT'), ('c', 'CREDIT')], max_length=1, verbose_name='type')),
                ('image', models.ImageField(default='images/default/jre.png', upload_to='images/jre/')),
                ('amount', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='journals', related_query_name='journal', to='accounting.coa')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jre_authors', related_query_name='jre_author', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='journals', related_query_name='journal', to='accounting.jrb', verbose_name='batch')),
                ('cashflow', models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', related_query_name='journal', to='accounting.ccf', verbose_name='cash flow')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jre_editors', related_query_name='jre_editor', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journals', related_query_name='journal', to='accounting.bsg')),
            ],
            options={
                'verbose_name': 'JRE',
                'verbose_name_plural': 'JRE',
                'ordering': ('-date', '-number'),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=125, unique=True)),
                ('number', models.CharField(default='000.000.000', max_length=30, unique=True, verbose_name='tax number')),
                ('legal', models.CharField(choices=[('ud', 'UD'), ('cv', 'CV'), ('pt', 'PT'), ('lc', 'LLC'), ('kp', 'Koperasi'), ('ys', 'Yayasan'), ('ot', 'Lainnya')], default='ot', max_length=3)),
                ('business_type', models.CharField(max_length=125)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=125)),
                ('country', models.CharField(max_length=125)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('config', models.JSONField(null=True)),
                ('image', models.ImageField(default='images/default/company.png', upload_to='images/accounting/company/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comp_authors', related_query_name='comp_author', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comp_editors', related_query_name='comp_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='COH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=125, unique=True, verbose_name='account header')),
                ('report', models.CharField(choices=[('bs', 'BALANCE SHEET'), ('es', 'EQUITY STATEMENT'), ('pl', 'PROFIT & LOSS'), ('hp', 'HELPER/NO-REPORT')], max_length=2)),
                ('group', models.IntegerField(choices=[(1, 'ASSET'), (2, 'LIABILITY'), (3, 'EQUITY'), (4, 'REVENUE'), (5, 'EXPENSE'), (6, 'GAIN'), (7, 'LOSES'), (9, 'OTHER')], verbose_name='account group')),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/default/coh.png', upload_to='images/accounting/coh/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coh_authors', related_query_name='coh_author', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coh_editors', related_query_name='coh_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'COH',
                'verbose_name_plural': 'COH',
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='coa',
            name='header',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', related_query_name='account', to='accounting.coh', verbose_name='account header'),
        ),
    ]
