# Generated by Django 4.0.4 on 2022-08-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coa',
            name='number',
            field=models.FloatField(unique=True),
        ),
    ]
