# Generated by Django 4.0.4 on 2022-08-23 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0002_alter_coa_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(unique=True)),
                ('name', models.CharField(max_length=125, unique=True, verbose_name='account name')),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('flow', models.CharField(choices=[('i', 'INFLOW'), ('o', 'OUTFLOW')], max_length=1)),
                ('activity', models.IntegerField(choices=[(1, 'OPERATING'), (2, 'INVESTING'), (3, 'FINANCING'), (4, 'OTHERS')])),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/default/CCF.png', upload_to='images/CCF/')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CCF',
                'verbose_name_plural': 'CCF',
                'ordering': ('number',),
            },
        ),
    ]
