# Generated by Django 4.0.4 on 2022-09-01 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_jre_options_jre_pair_alter_jre_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jre',
            name='pair',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.jre'),
        ),
    ]
