# Generated by Django 4.0.4 on 2022-08-24 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0003_ccf'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(unique=True)),
                ('name', models.CharField(max_length=125, unique=True, verbose_name='account name')),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('group', models.CharField(max_length=125, verbose_name='type')),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/default/BSG.png', upload_to='images/BSG/')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BSG',
                'verbose_name_plural': 'BSG',
                'ordering': ('number',),
            },
        ),
    ]
