# Generated by Django 4.0.4 on 2022-09-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_comp_level_profile_comp_stat_and_more'),
        ('accounting', '0004_alter_jre_pair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jre',
            options={'ordering': ('-date', '-number', '-group'), 'verbose_name': 'JRE', 'verbose_name_plural': 'JRE'},
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
