# Generated by Django 4.0.4 on 2022-09-06 01:31

import accounting.controllers.jre
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_jre_options_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jre',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[accounting.controllers.jre.JRE.date_validator]),
        ),
    ]
