# Generated by Django 4.0.4 on 2022-08-25 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0005_jrb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coa',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', related_query_name='account', to='accounting.coh', verbose_name='account header'),
        ),
        migrations.CreateModel(
            name='JRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ref', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('group', models.CharField(choices=[('d', 'DEBIT'), ('c', 'CREDIT')], max_length=1, verbose_name='type')),
                ('image', models.ImageField(default='images/default/JRE.png', upload_to='images/JRE/')),
                ('amount', models.IntegerField(max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='journals', related_query_name='journal', to='accounting.coa')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', related_query_name='journal', to='accounting.jrb', verbose_name='batch')),
                ('cashflow', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='journals', related_query_name='journal', to='accounting.ccf', verbose_name='cash flow')),
                ('segment', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='journals', related_query_name='journal', to='accounting.bsg')),
            ],
            options={
                'verbose_name': 'JRE',
                'verbose_name_plural': 'JRE',
                'ordering': ('date',),
            },
        ),
    ]
