# Generated by Django 4.0.4 on 2022-09-11 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_jre_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jre',
            name='batch',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='journals', related_query_name='journal', to='accounting.jrb', verbose_name='batch'),
        ),
    ]
