# Generated by Django 4.0.4 on 2022-08-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_coa_header_jre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jre',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
