# Generated by Django 4.0.4 on 2022-09-12 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_jre_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jre',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
