# Generated by Django 4.0.4 on 2022-08-26 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0008_company_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsg',
            name='edited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_bsgs', related_query_name='edited_bsg', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ccf',
            name='edited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_ccfs', related_query_name='edited_ccf', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coa',
            name='edited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_coas', related_query_name='edited_coa', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coh',
            name='edited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_cohs', related_query_name='edited_coh', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='edited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_companys', related_query_name='edited_company', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jrb',
            name='edited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_jrbs', related_query_name='edited_jrb', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jre',
            name='edited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_jres', related_query_name='edited_jrb', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jre',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bsg',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_bsgs', related_query_name='created_bsg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ccf',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_ccfs', related_query_name='created_ccf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coa',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_coas', related_query_name='created_coa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coa',
            name='header',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='accounts', related_query_name='account', to='accounting.coh', verbose_name='account header'),
        ),
        migrations.AlterField(
            model_name='coh',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_cohs', related_query_name='created_coh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_companys', related_query_name='created_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jrb',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_jrbs', related_query_name='created_jrb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jre',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_jres', related_query_name='created_jrb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jre',
            name='batch',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='journals', related_query_name='journal', to='accounting.jrb', verbose_name='batch'),
        ),
    ]
