# Generated by Django 4.0.4 on 2022-08-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_bsg_edited_by_ccf_edited_by_coa_edited_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='jrb',
            options={'verbose_name': 'JRB', 'verbose_name_plural': 'JRB'},
        ),
        migrations.AlterField(
            model_name='jre',
            name='cashflow',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', related_query_name='journal', to='accounting.ccf', verbose_name='cash flow'),
        ),
    ]
