# Generated by Django 4.0.4 on 2022-08-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_alter_jre_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coh',
            name='report',
            field=models.CharField(choices=[('bs', 'balance sheet'), ('es', 'equity statement'), ('pl', 'profit & loss'), ('hp', 'helper/no-report')], default='bs', max_length=2),
            preserve_default=False,
        ),
    ]
