# Generated by Django 4.0.4 on 2022-08-30 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0014_coh_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='jre',
            options={'ordering': ('-date', '-number'), 'verbose_name': 'JRE', 'verbose_name_plural': 'JRE'},
        ),
        migrations.AlterField(
            model_name='bsg',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bsg_authors', related_query_name='bsg_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bsg',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bsg_editors', related_query_name='bsg_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bsg',
            name='image',
            field=models.ImageField(default='images/default/bsg.png', upload_to='images/bsg/'),
        ),
        migrations.AlterField(
            model_name='ccf',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ccf_authors', related_query_name='ccf_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ccf',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ccf_editors', related_query_name='ccf_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ccf',
            name='image',
            field=models.ImageField(default='images/default/ccf.png', upload_to='images/accounting/ccf/'),
        ),
        migrations.AlterField(
            model_name='coa',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coa_authors', related_query_name='coa_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coa',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coa_editors', related_query_name='coa_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coa',
            name='image',
            field=models.ImageField(default='images/default/coa.png', upload_to='images/accounting/coa/'),
        ),
        migrations.AlterField(
            model_name='coh',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coh_authors', related_query_name='coh_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coh',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coh_editors', related_query_name='coh_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coh',
            name='image',
            field=models.ImageField(default='images/default/coh.png', upload_to='images/accounting/coh/'),
        ),
        migrations.AlterField(
            model_name='coh',
            name='report',
            field=models.CharField(choices=[('bs', 'BALANCE SHEET'), ('es', 'EQUITY STATEMENT'), ('pl', 'PROFIT & LOSS'), ('hp', 'HELPER/NO-REPORT')], max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comp_authors', related_query_name='comp_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comp_editors', related_query_name='comp_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jrb',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jrb_authors', related_query_name='jrb_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jrb',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jrb_editors', related_query_name='jrb_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jrb',
            name='image',
            field=models.ImageField(default='images/default/jrb.png', upload_to='images/jrb/'),
        ),
        migrations.AlterField(
            model_name='jre',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jre_authors', related_query_name='jre_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jre',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jre_editors', related_query_name='jre_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jre',
            name='image',
            field=models.ImageField(default='images/default/jre.png', upload_to='images/jre/'),
        ),
    ]
